### ISSUE TITLE
Cannot read properties of undefined (reading 'error')

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/ifctool#15]
(base) markussteinbrecher@MacBook-Pro-3 Seestrasse % npx @bldrs-ai/ifctool@beta Seestrasse.ifc --type=IFCWALL
Need to install the following packages:
  @bldrs-ai/ifctool@beta
Ok to proceed? (y) y
/Users/markussteinbrecher/.npm/_npx/fe9b048579684b87/node_modules/web-ifc/web-ifc-api-node.js:6175
              throw ex;
              ^

TypeError: Cannot read properties of undefined (reading 'error')
    at internalError (file:///Users/markussteinbrecher/.npm/_npx/fe9b048579684b87/node_modules/@bldrs-ai/ifctool/src/utils.js:15:12)
    at processArgs (file:///Users/markussteinbrecher/.npm/_npx/fe9b048579684b87/node_modules/@bldrs-ai/ifctool/src/main.js:101:7)
    at async file:///Users/markussteinbrecher/.npm/_npx/fe9b048579684b87/node_modules/@bldrs-ai/ifctool/src/main.js:117:20
(base) markussteinbrecher@MacBook-Pro-3 Seestrasse %

**Comment by pablo-mayrgundter** [comment]
Fixed in #14
