### ISSUE TITLE
Built tool fails on dynamic import

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/ifctool#19]
I'm guessing it's log4js, but not sure
```
> yarn build && node dist/main.js
file:///Users/pablo/bldrs-ai/ifctool/dist/main.js:14
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "tty" is not supported
    at file:///Users/pablo/bldrs-ai/ifctool/dist/main.js:14:9
    at node_modules/debug/src/node.js (file:///Users/pablo/bldrs-ai/ifctool/dist/main.js:610:15)
```

**Comment by pablo-mayrgundter** [comment]
Repurposed esbuild to build for web instead of node.  Node might be nice but no need for now.
